jwt:
  secret: "papiSimplonSenegal1998@2022"

server:
  port: 8081
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_  supportportal?createDatabaseIfNotExist=true
    password: papi
    username: papi
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false